"""add sources to queries

Revision ID: 5d4e754b23d3
Revises: 780209cb7827
Create Date: 2026-07-28 12:28:23.176267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d4e754b23d3'
down_revision: Union[str, Sequence[str], None] = '780209cb7827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('sources', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'sources')
    # ### end Alembic commands ###
